<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Materias_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get materia by idMateria
     */
    function get_materia($idMateria)
    {
        return $this->db->get_where('materias',array('idMateria'=>$idMateria))->row_array();
    }
        
    /*
     * Get all materias
     */
    function get_all_materias()
    {
        //$this->db->order_by('idMateria', 'desc');
        $this->db->select('m.*, p.nombreProfesor');
        $this->db->from('materias as m');
        $this->db->join('profesores as p', 'm.idProfesor = p.idProfesor');
        $this->db->order_by('idMateria', 'desc');
        return $this->db->get('materias')->result_array();
    }
        
    /*
     * function to add new materia
     */
    function add_materia($params)
    {
        $this->db->insert('materias',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update materia
     */
    function update_materia($idMateria,$params)
    {
        $this->db->where('idMateria',$idMateria);
        return $this->db->update('materias',$params);
    }
    
    /*
     * function to delete materia
     */
    function delete_materia($idMateria)
    {
        return $this->db->delete('materias',array('idMateria'=>$idMateria));
    }
}
