<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Profesores_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get profesor by idProfesor
     */
    function get_profesor($idProfesor)
    {
        return $this->db->get_where('profesores',array('idProfesor'=>$idProfesor))->row_array();
    }
        
    /*
     * Get all profesores
     */
    function get_all_profesores()
    {
        $this->db->order_by('idProfesor', 'desc');
        return $this->db->get('profesores')->result_array();
    }
        
    /*
     * function to add new profesor
     */
    function add_profesor($params)
    {
        $this->db->insert('profesores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update profesor
     */
    function update_profesor($idProfesor,$params)
    {
        $this->db->where('idProfesor',$idProfesor);
        return $this->db->update('profesores',$params);
    }
    
    /*
     * function to delete profesor
     */
    function delete_profesor($idProfesor)
    {
        return $this->db->delete('profesores',array('idProfesor'=>$idProfesor));
    }
}
